project_name: grepfiles
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/grepfiles
    binary: grepfiles
    id: grepfiles_CGO_ENABLED
    ldflags:
      - -s -w
      - -X github.com/kawakatz/grepfiles/cmd/grepfiles.Version={{.Version}}
      - -X github.com/kawakatz/grepfiles/cmd/grepfiles.Revision={{.ShortCommit}}
      - -X github.com/kawakatz/grepfiles/cmd/grepfiles.BuildTag={{.Tag}}
    goos:
      - darwin
    goarch:
      - amd64
    ignore:
      - goos: linux
        goarch: arm64
    env:
      - CGO_ENABLED=1
  - main: ./cmd/grepfiles
    binary: grepfiles
    id: grepfiles
    ldflags:
      - -s -w
      - -X github.com/kawakatz/grepfiles/cmd/grepfiles.Version={{.Version}}
      - -X github.com/kawakatz/grepfiles/cmd/grepfiles.Revision={{.ShortCommit}}
      - -X github.com/kawakatz/grepfiles/cmd/grepfiles.BuildTag={{.Tag}}
    ignore:
      - goos: linux
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto